const ROLES = { SUPER_ADMIN: 'SUPER_ADMIN', BUSINESS_ADMIN: 'BUSINESS_ADMIN' };

const CONTENT_STATUS = { DRAFT: 'DRAFT', PENDING: 'PENDING', PUBLISHED: 'PUBLISHED', REJECTED: 'REJECTED' };
const CONTENT_STATUS_LIST = Object.values(CONTENT_STATUS);

const CATEGORY_STATUS_LIST = ['ACTIVE', 'INACTIVE'];
const VIDEO_TYPES = ['YOUTUBE', 'UPLOAD'];
const NOTIFICATION_TYPES = { NEW_ANSWER: 'NEW_ANSWER' };

const LANGUAGES = ['en', 'ta']; // English, Tamil

module.exports = {
  ROLES,
  CONTENT_STATUS,
  CONTENT_STATUS_LIST,
  CATEGORY_STATUS_LIST,
  VIDEO_TYPES,
  NOTIFICATION_TYPES,
  LANGUAGES,
};
